# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13f14dc35f3c8deb700431fb1f4503c94f211c9b10a2a828e0205b49b20d5c24b0791a92a179c7040ad3ef67b0611e2f8ca2d66b30093b0ba9c63ccf109678d9

test:
  secret_key_base: ff2a1b7362b35688b060dc596be4e9c205bc36f9df0b73bd1bb2e0ffcebe18569f03cc9af62db77d27db589b7525e6d27b38de3b1e14f3ff1f79d33d3a484c85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
